title: Shamanta Rezwana
logo: passport size.png
author:
  Address: Vadail Bazar, DEPZ, Savar, Dhaka, Bangladesh  
  email: "rezwanashamanta@gmail.com"
  github: "https://github.com/anRez10A"
  linkedin: "https://www.linkedin.com/in/s-rezwana10a/"
  Contact No: "+8801703800280"
theme:  jekyll-theme-minimal
